name: RailOps Full Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *' # Daily at 23:30 Adelaide time (14:00 UTC)

jobs:
  login-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      - name: Login to TrainFinder and Upload Cookie
        env:
          TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
          TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python trainfinder_login_username.py
          python update_secret.py

  update-trains-loop:
    needs: login-and-update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Update Trains (Loop)
        env:
          TRAINFINDER_COOKIE: ${{ secrets.TRAINFINDER_COOKIE }}
        run: |
          python update_trains_loop.py
