name: Full RailOps Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  run-updater:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Run auto-login and upload cookie
        env:
          TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
          TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python trainfinder_login_username.py
          python update_secret.py

      - name: Run train updater
        run: |
          python update_trains_loop.py
