name: Manual Cookie Refresh

on:
  workflow_dispatch:

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run login script to refresh cookie
        env:
          TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
          TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
        run: |
          python trainfinder_login_username.py
          echo "✅ .ASPXAUTH cookie saved locally."
          echo "==== COPY BELOW AND UPDATE IN GITHUB SECRETS ===="
          cat cookie.txt
          echo "==== END COOKIE ===="
