name: Publish trains.json to Netlify

on:
  push:
    paths:
      - 'trains.json'
      - '.github/workflows/publish-netlify.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          rm -rf out_data
          mkdir -p out_data
          cp -f trains.json out_data/trains.json
          # CORS + caching headers
          cat > out_data/_headers <<'HDR'
          /trains.json
            Access-Control-Allow-Origin: *
            Cache-Control: no-store, max-age=0
          HDR

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Netlify CLI
        run: npm i -g netlify-cli

      - name: Deploy to Netlify (prod)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy \
            --dir=out_data \
            --prod \
            --site "$NETLIFY_SITE_ID" \
            --auth "$NETLIFY_AUTH_TOKEN" \
            --message "Deploy trains.json via GitHub Actions"
