name: Auto-Refresh TrainFinder Cookie

permissions:
  contents: read
  actions: write

on:
  schedule:
    - cron: '0 16 * * *'  # Daily at 2:30 AM Adelaide
  workflow_dispatch:

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install selenium

    - name: Run TrainFinder login script
      env:
        TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
        TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
      run: |
        python trainfinder_login_username.py
        echo "COOKIE_VALUE=$(cat cookie.txt)" >> $GITHUB_ENV

    - name: Update TRAINFINDER_COOKIE
      uses: hmanzur/actions-set-secret@v2.0.0
      with:
        name: TRAINFINDER_COOKIE
        value: ${{ env.COOKIE_VALUE }}
        repository: ${{ github.repository }}
