name: 🔐 Refresh TrainFinder Cookie (Daily)

on:
  schedule:
    - cron: "0 0 * * *"   # daily at 00:00 UTC
  workflow_dispatch:

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
      TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: 🔑 Log in and refresh cookie.txt
        run: |
          python scripts/trainfinder_login.py "${TRAINFINDER_USERNAME}" "${TRAINFINDER_PASSWORD}"

      - name: 💾 Commit cookie.txt (if changed)
        run: |
          git config --global user.name "RailOps Auto-Login"
          git config --global user.email "railops-bot@users.noreply.github.com"
          git add cookie.txt debug/*.*
          git commit -m "Auto-refresh cookie $(date -u)" || echo "No changes"
          git push || true

      - name: 📤 Upload debug (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cookie-debug
          path: debug/**
          if-no-files-found: ignore
