name: Auto-Refresh TrainFinder Cookie

permissions:
  contents: read
  actions: write

on:
  schedule:
    - cron: '0 16 * * *'  # Daily at 2:30 AM Adelaide
  workflow_dispatch:

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install selenium

    - name: Run TrainFinder login script
      env:
        TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
        TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
      run: |
        python trainfinder_login_username.py
        echo "COOKIE_VALUE=$(cat cookie.txt)" >> $GITHUB_ENV

    - name: Install tweetsodium for encryption
      run: npm install tweetsodium

    - name: Update TRAINFINDER_COOKIE secret
      uses: actions/github-script@v7
      with:
        script: |
          const sodium = require('tweetsodium');
          const newCookie = process.env.COOKIE_VALUE;
          if (!newCookie || newCookie.length < 50) {
            core.setFailed("❌ Cookie is empty or invalid");
          } else {
            const { data: publicKey } = await github.rest.actions.getRepoPublicKey({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const messageBytes = Buffer.from(newCookie);
            const keyBytes = Buffer.from(publicKey.key, 'base64');
            const encryptedBytes = sodium.seal(messageBytes, keyBytes);
            const encryptedValue = Buffer.from(encryptedBytes).toString('base64');
            await github.rest.actions.createOrUpdateRepoSecret({
              repository: context.repo.repo,
              owner: context.repo.owner,
              secret_name: "TRAINFINDER_COOKIE",
              encrypted_value: encryptedValue,
              key_id: publicKey.key_id
            });
            core.info("✅ TRAINFINDER_COOKIE updated successfully");
          }
