name: Auto-Refresh TrainFinder Cookie

on:
  schedule:
    - cron: '0 16 * * *'  # Daily at 2:30 AM Adelaide
  workflow_dispatch:

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      secrets: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install selenium

    - name: Run TrainFinder login script
      env:
        TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
        TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
      run: |
        python trainfinder_login_username.py
        echo "COOKIE_VALUE<<EOF" >> $GITHUB_ENV
        cat cookie.txt >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Update TRAINFINDER_COOKIE secret
      uses: actions/github-script@v7
      with:
        script: |
          const newCookie = process.env.COOKIE_VALUE;
          if (!newCookie || newCookie.length < 50) {
            core.setFailed("❌ Cookie is empty or invalid");
          } else {
            await github.rest.actions.updateRepoSecret({
              repository: context.repo.repo,
              owner: context.repo.owner,
              secret_name: "TRAINFINDER_COOKIE",
              encrypted_value: newCookie,
              key_id: (await github.rest.actions.getRepoPublicKey({
                owner: context.repo.owner,
                repo: context.repo.repo
              })).data.key_id
            });
            core.info("✅ TRAINFINDER_COOKIE updated successfully");
          }
