name: Refresh TrainFinder Cookie

on:
  schedule:
    - cron: '00 23 * * *'  # Runs daily at 8:30 AM Adelaide time (23:00 UTC)
  workflow_dispatch:

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install selenium pynacl requests
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Download Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb -y

    - name: Run TrainFinder login
      env:
        TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
        TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
      run: python trainfinder_login_username.py

    - name: Update GitHub Secret with Cookie
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python update_secret.py