name: Refresh TrainFinder Cookie

on:
  schedule:
    - cron: '0 1 * * *'  # Daily at 1:00 AM UTC
  workflow_dispatch:

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium pynacl requests
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          if [ ! -e /usr/bin/chromedriver ]; then sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver; fi

      - name: Run login script
        env:
          TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
          TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}
        run: python trainfinder_login_username.py

      - name: Update GitHub Secret
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python update_secret.py

      - name: Trigger Netlify Build
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_API_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
        run: |
          curl -X POST https://api.netlify.com/build_hooks/${NETLIFY_SITE_ID} \
            -H "Authorization: Bearer $NETLIFY_API_TOKEN"