name: TrainFinder Updater

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  update-trains:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run updater
        env:
          COOKIE_VALUE: ${{ secrets.TRAINFINDER_COOKIE }}
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: python update_trains_loop.py
