name: Update Train Data

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TRAINFINDER_COOKIE: ${{ secrets.TRAINFINDER_COOKIE }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run train updater
        run: python update_trains_autozoom.py

      - name: Commit updated trains.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add trains.json
          git commit -m "Update trains.json [bot]" || echo "No changes to commit"
          git push

      - name: Trigger Netlify build
        run: |
          curl -X POST -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
          https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/builds