name: Refresh and Upload TrainFinder Cookie

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"  # runs daily at 7:30am SA time (21:00 UTC)

jobs:
  refresh-cookie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install selenium pynacl requests
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          wget https://storage.googleapis.com/chrome-for-testing-public/136.0.7103.92/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver

      - name: Log in to TrainFinder
        run: python trainfinder_login_username.py
        env:
          TRAINFINDER_USERNAME: ${{ secrets.TRAINFINDER_USERNAME }}
          TRAINFINDER_PASSWORD: ${{ secrets.TRAINFINDER_PASSWORD }}

      - name: Upload Cookie to GitHub Secrets
        run: python update_secret.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}